### ISSUE TITLE
Good plot are marked as invalid plot [BUG]

### ISSUE THREAD

**Issue by vicmic** [ChainGreenOrg/chaingreen-blockchain#51]
I have 227 plot farmed on chia official block chain and other forks of chia offical blockchain.
All plots are ok for the others blockchain but all plots are make as invalid on chaingreen.

On the log i get this error:

2021-06-24T08:33:19.971 harvester chaingreen.plotting.plot_tools: ERROR    Failed to open file K:\plot-k32-2021-06-24-06-10-0c7f02cfe2adebcb85c8fb60140fb6da1376102e0388b76b48428e2a2186c894.plot. badbit or failbit after reading size 104 at position 0 Traceback (most recent call last):
  File "chaingreen\plotting\plot_tools.py", line 189, in process_file
RuntimeError: badbit or failbit after reading size 104 at position 0

**Comment by dfunked** [comment]
Using hpool by any chance? That thing seriously messes with plots.

Stop hpool miner and run the checks again.

**Comment by vicmic** [comment]
Yes, I'm using HPool.
In fact, after closing the HPool farmer, the plots have been validated, but I don't understand why with all the other coins that use the same plots are ok and only with ChainGreen they are not accepted if the HPool farmer is open.

**Comment by dfunked** [comment]
Like I said, hpool does weird stuff with plots. Best rule of thumb is to only give it read only access to plots, and to only start the hpool miner after everything else that uses the plots is already running.

Others have experienced it with Chia and other forks, so it's really not a chaingreen specific thing. Just like with Chia, the devs shouldn't be expected to fix issues that you've caused by running an unofficial client.
